server:
  port: 8082
spring:
  application:
    name: "Reports"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: "dev"
  intercom:
    requests:
      host: "${SPRING_MS_REQUESTS}"
    auth:
      host: "${SPRING_MS_AUTHENTICATION}"
    
aws:
  dynamodb:
    endpoint: "${SPRING_DYNAMODB_ENDPOINT}"
    region: "${SPRING_DYNAMODB_REGION}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
